### ISSUE TITLE
Find an online site design tool

### ISSUE THREAD

**Issue by scott-steadman** [scott-steadman/se-registry#17]
# Summary
I'd like to see what kinds of design tools are out there and use them to create layouts for the registry.

# Work
## Research
- [x] Evaluate [balsamiq](https://balsamiq.com/) (paid)
- [x] Evaluate  [fluidui](https://www.fluidui.com/) (paid)
- [x] Evaluate [marvelapp](https://marvelapp.com/) (free tier)
- [x] Evaluate [mockflow](https://www.mockflow.com/) (free tier)
- [x] Evaluate [moqups](https://moqups.com/) (paid)

# Notes

**Comment by ss** [comment]
[Balsamiq](https://www.balsamiq.com)
- Nice intro to wire-framing tutorial

**Comment by scott-steadman** [comment]
None of these really met my need.

I'm going to keep an eye out for sites whose look I like.

I'm also going to try generating HTML 5 with semantic elements.
